name: Testing

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.7, 3.8, 3.9]
                redis-version: [5, 6]

        steps:
        - name: Git checkout
          uses: actions/checkout@v2

        - name: Set up Python ${{ matrix.python-version }}
          uses:
          with:

        - name: Start Redis ${{ matrix.redis-version }}
          uses:
          with:

        - name: Install dependencies
          run: |
            sudo apt-get install python3-dev
            python -m pip install --upgrade pip
            pip install pytest pytest-cov pytest-asyncio
            pip install flake8 codecov mypy

        - name: Lint with Flake8
          run: |
            flake8 .

        - name: Mypy
          run: |
            mypy .

        - name: Test with Pytest
          run: |
            python -m pytest .
